### PR TITLE
Update to version 1.2.8p24

### PR DESCRIPTION
**Pull request by ganto**
There is still another 1.2.8 update. Use it as long as the 1.4.0 setup is not ready yet.

### CODE REVIEW

**Comment by drybjed** [comment]
Any idea why the build fails on the WATO task? Is that the first use of `template_src` lookup in the role? The `debops` Python module is installed by Travis earlier, so I would think that would work...

**Comment by ganto** [comment]
Actually, I have no idea. It really looks as `lookup("template_src", ...)` must be the cause. Maybe an upstream bug? Do you see this anywhere else? Tried to check the Jinja templates used in this task, but I can't find the string `debops` being used there.

Just for reference:

**Error:**
```
TASK [ansible-checkmk_server : Generate Check_MK WATO Multisite definitions] ***

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named debops

fatal: [testing-gce-c65c4ee3-ba83-4871-a453-d48ed7eb95a9]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
```

**Ansible:**
```
ansible 2.3.2.0 (stable-2.3 0c8459b01b) last updated 2017/07/04 15:42:31 (GMT +000)
  config file = /home/travis/build/debops-contrib/ansible-checkmk_server/rolespec/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

**DebOps:**
```
Collecting debops
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading debops-0.4.4.tar.bz2
Collecting netaddr (from debops)
  Downloading netaddr-0.7.19-py2.py3-none-any.whl (1.6MB)
    100% |████████████████████████████████| 1.6MB 831kB/s 
Requirement already satisfied: argparse in /usr/lib/python2.7 (from debops)
Requirement already satisfied: passlib in /usr/lib/python2.7/dist-packages (from debops)
Installing collected packages: netaddr, debops
  Running setup.py install for debops ... done
Successfully installed debops-0.4.4 netaddr-0.7.19
```

**Comment by drybjed** [comment]
@ganto: I've found out why the test failed. I switched some time ago to using Ansible in a virtualenv, because Trusty jinja 2.9 resulted in failed tests, as it does. The `debops` Python module was not installed in that virtualenv. Now it's added, and the lookup plugins should work again. Sorry for the confusion. :-)

**Comment by ganto** [comment]
Thanks for the feedback. I also found it out yesterday evening 😉  when I started to cleanup the `defaults.conf` a bit for Trusty. See https://github.com/ganto/debops-test-suite/commit/2dbbc299f7f3a1e418e15b830f43145fca097a42. 

Any plan to switch the tests run to Trusty by default? I also found another issue [here](https://github.com/nickjj/rolespec/pull/44).

**Comment by drybjed** [comment]
I don't see why not, but that's done at the `.travis.yml` level, ie. in each role separately. I'm currently a bit busy with a deadline for a few roles, and I don't have time for a mass-signing of role PRs... Let's give it some time.

**Comment by ganto** [comment]
Ok, if I'll touch something, I'll already test with Trusty. I guess there will still pop up some issues here and there as the examples above show.

**Pull request merged**
